name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H impromat.app >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git remote add dokku dokku@impromat.app:agent-land
          git push dokku main:master --force
